### ISSUE TITLE
Missing Lyn

### ISSUE THREAD

**Issue by ZeitD** [NoviceCoder2000/Fire-Emblem-Civilizations#1]
**sup!**
Well, I like to see the updates ingame (of the mods) using the civilopedia, knowing this, here:
![image](https://user-images.githubusercontent.com/105519034/187257383-5eeca842-2768-4251-a929-667428283a82.png)
I was trying to play with Sacaean "to play with Lyn", but then I was unable to build the Manikatti Shrine or find it

The Lyn upgrade for renaissance is missing, but I was looking more in the updates and:
![image](https://user-images.githubusercontent.com/105519034/187261563-3dd77440-6b7d-484b-b5de-08896c6efbf1.png)

Idk if it is mean to be this way, my game is buged/missing files, or u already know of the "issue", if it was of any help let me know, I like your work for the mod so much man!! Same for the advanced wars one!!!

**Comment by NoviceCoder2000** [comment]
Hey there! I have fixed the embarrassing incorrect misspelling for the Mani Katti Shrine's "uniqueTo"
Also fixed the Renaissance version of Lyn. It seems to be working perfectly on my end now. If it works to you as well, feel free to close this issue.

And yes, this issue was real helpful to me :)
