### ISSUE TITLE
Failure to launch after install

### ISSUE THREAD

**Issue by MrSteamie** [NoviceCoder2000/Fire-Emblem-Civilizations#2]
![Screenshot_20230102-154222](https://user-images.githubusercontent.com/121829129/210276733-11c92319-6e54-4c6d-8be9-5939c296e411.png)

Tried downloading the mod again after a long while since I last used it, phone was reset from last time I used it so clean install as far as old versions of the mod goes. 
However, it now fails to function after download. Not recognizing the sword tag is puzzling because it definitely worked for some other mods I have. 
Sorry for the sparse info
-MrSteamie

**Comment by NoviceCoder2000** [comment]
Uniques are deprecated, nothing to worry about. Fix is otw.

**Comment by NoviceCoder2000** [comment]
Well it took some time, and tested the new update a bit, this should fix the problem. If you see any more problem within the mod or issue regarding the balance, don't hesitate to open up a issue.
